archive:
  files:
  - LICENSE
  format: tar.gz
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    386:    32bit
    amd64:  64bit

    darwin: macOS
    linux:  Linux

brew:
  caveats: Use `forward pod [local:]remote`
  commit_author:
    name:  Kamil Samigullin
    email: kamil@samigullin.info
  description: Extended kubectl port-forward - multiple port forwarding simultaneously.
  folder: Formula
  github:
    name:  homebrew-tap
    owner: kamilsk
  homepage: https://github.com/kamilsk/forward
  name: forward

build:
  binary: forward
  env:
  - CGO_ENABLED=0
  goarch:
  - 386
  - amd64
  goos:
  - darwin
  - linux
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  main: .

checksum: { name_template: checksums.txt }

release:
  draft: false
  github:
    name:  forward
    owner: kamilsk
