language: go

go:
- master
- 1.x
- 1.11.x
- 1.12.x

sudo: false

before_install:
- export GO111MODULE=on
- export GOFLAGS=-mod=vendor

script:
- make test

after_success:
- echo $TRAVIS_GO_VERSION ":" $TRAVIS_TAG
- if [[ $TRAVIS_GO_VERSION == 1.12* ]] && [ -n "$TRAVIS_TAG" ]; then curl -sL https://git.io/goreleaser | bash; fi

notifications:
  slack: octolab:1eMS7IqOArBipiu31jYVd0cN
