language: go

go:
- master
- 1.x
- 1.10.x
- 1.11.x
- 1.12.x

sudo: false

before_install:
- export GO111MODULE=on
- export GOFLAGS=-mod=vendor
- export CODECLIMATE=https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64

before_script:
- echo $TRAVIS_GO_VERSION ":" $TRAVIS_TAG
- if [[ $TRAVIS_GO_VERSION == 1.12* ]]; then curl -L $CODECLIMATE > bin/cc-test-reporter; fi
- if [[ $TRAVIS_GO_VERSION == 1.12* ]]; then chmod +x bin/cc-test-reporter; fi
- if [[ $TRAVIS_GO_VERSION == 1.12* ]]; then bin/cc-test-reporter before-build; fi

script:
- if [[ $TRAVIS_GO_VERSION == 1.12* ]]; then make test-with-coverage-profile; else make test; fi

after_success:
- if [[ $TRAVIS_GO_VERSION == 1.12* ]]; then bin/cc-test-reporter after-build -t gocov --exit-code $TRAVIS_TEST_RESULT; fi
- if [[ $TRAVIS_GO_VERSION == 1.12* ]] && [ -n "$TRAVIS_TAG" ]; then curl -sL https://git.io/goreleaser | bash; fi

notifications:
  slack: octolab:1eMS7IqOArBipiu31jYVd0cN
